name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Wrangler
        run: npm install -g wrangler  # 安装最新版本 的 wrangler

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy Vless_workers_pages/_worker.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
