name: Deploy Specific File to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy specific file to workspace
        run: cp Vless_workers_pages/_worker.js ./specific-file.js

      # 不再需要为文件设置执行权限，因为它不会直接被执行
      # - name: Set file permissions
      #   run: chmod +x ./specific-file.js

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          entryPoint: ./specific-file.js  # 部署文件路径
