name: Deploy to Cloudflare Workers

# 触发条件，这里设置为推送到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 Wrangler CLI
      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      # 登录到 Cloudflare
      - name: Authenticate with Cloudflare
        run: wrangler login --api-token ${{ secrets.CF_API_TOKEN }}

      # 发布 Worker
      - name: Publish Worker
        run: wrangler publish --script Vless_workers_pages/_worker.js --name stash
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
