name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # 根据你的主分支设置

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 设置 Node.js 版本

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker
        run: npx wrangler deploy Vless_workers_pages/_worker.js --compatibility-date $(date +%Y-%m-%d) --name "stash"

